### ISSUE TITLE
peer dependency issues

### ISSUE THREAD

**Issue by dacbd** [octokit/plugin-paginate-rest.js#418] opened 2022-07-21 01:54 UTC
Hi all, I recently went through some package updating in a project, and found that you have updated your `ocktokit/core` to `v4` on [`v2.21.2`](https://github.com/octokit/plugin-paginate-rest.js/releases/tag/v2.21.2) and then did a subsequent `v3` that dropped the old node version support. Shouldn't that peer update have happened in your `v3` release and not as a final patch release on `v2`?

I can probably work on my own updates to fix the `npm install` issue, but it is inconvenient.

**Comment by wolfy1339** [comment] 2022-07-21 02:04
Yes, it should have happened in the `v3` release.

Can you pin the version to `2.21.1`? The `2.21.2` update didn't contain any other updates

**Comment by dacbd** [comment] 2022-07-21 02:17
@wolfy1339 requiring and pining to `2.21.1` did resolve the issue

**Comment by oscard0m** [comment] 2022-07-21 09:44
Should we close this issue @dacbd ?

@wolfy1339 do you want me to edit https://github.com/octokit/plugin-paginate-rest.js/releases/v2.21.2 Release notes to add alert users about this?

**Comment by gr2m** [comment] 2022-07-21 22:45
@dacbd can you confirm that the problem is resolved please?

**Closed** 2022-07-22 16:02 UTC
Labels: bug, released on @2.x
